const products = [
  {
    id: 'f788voipXg43w3vP2',
    title: 'Modern Glow',
    brand: 'Illumix',
    image: 'images/lamp-1.jpg',
    price: 17.99,
  },
  {
    id: '9pHf2RIfto4Cb7aFh',
    title: 'Luxe Lamp',
    brand: 'Glowora',
    image: 'images/lamp-2.jpg',
    price: 21.20,
  },
  {
    id: 't79kCmkSiMkbki8ko',
    title: 'Soft Shade',
    brand: 'Brighture',
    image: 'images/lamp-3.jpg',
    price: 18.80,
  },
  {
    id: '1uL4ICqBohot4QQsI',
    title: 'Bright Sphere',
    brand: 'Brighture',
    image: 'images/lamp-4.jpg',
    price: 15.99,
  },
  {
    id: 'zW3yRZnbDG1JopRHp',
    title: 'Classic Beam',
    brand: 'Illumix',
    image: 'images/lamp-5.jpg',
    price: 19.99,
  },
  {
    id: 'pX2NkjFhSWw3GyP7q',
    title: 'Night Lighter',
    brand: 'Glowora',
    image: 'images/lamp-6.jpg',
    price: 18.99,
  },
  {
    id: '9AL5bbY4AEsZEougx',
    title: 'Ambient Aura',
    brand: 'Glowora',
    image: 'images/lamp-7.jpg',
    price: 16.99,
  },
  {
    id: 'mJ2d7svjMK1jgTb2l',
    title: 'Cozy Glow',
    brand: 'LuminEdge',
    image: 'images/lamp-8.jpg',
    price: 19.99,
  },
  {
    id: 'Vg6mg2JNZhua1ctaE',
    title: 'Elegant Shine',
    brand: 'Brighture',
    image: 'images/lamp-9.jpg',
    price: 21.50,
  },
  {
    id: '63PvKMw0bEt3NR3YF',
    title: 'Timber Light',
    brand: 'Illumix',
    image: 'images/lamp-10.jpg',
    price: 16.99,
  },
  {
    id: 'mC3xa539XFy5IWsgM',
    title: 'Sleek Lume',
    brand: 'LuminEdge',
    image: 'images/lamp-11.jpg',
    price: 17.95,
  },
  {
    id: '54YyqNGtOtRglG4Q5',
    title: 'Radiant Touch',
    brand: 'LuminEdge',
    image: 'images/lamp-12.jpg',
    price: 22.50,
  },
  {    
    id: 'rTY5qtOtIpj78oPlh',
    title: 'Glass Glimmer',
    brand: 'LuminEdge',
    image: 'images/lamp-13.jpg',
    price: 19.99,
  },
];
